import React, { Component } from 'react';
import * as d3 from 'd3';
import faker from 'faker';
import { Container, Row, Col } from 'react-bootstrap';

import { getGeneratedStatisticByCourses } from './autoGeneratedMockData';

const mockData = getGeneratedStatisticByCourses();
console.log(mockData);

function visualizeData() {
  const mapStudentByYearRange = (course) => {
    const { year1, year2, year3, year4 } = course.quantityStudent;
    const totalAmountOfStudent = year1 + year2 + year3 + year4;
    return d3.scaleLinear().domain([0, totalAmountOfStudent]).range([0, 280]);
  };

  let preRender = d3.select('#my-viz').selectAll('div').style('display', 'flex').style('justify-content', 'flex-start').data(mockData.allSems).enter();

  let renderSems = preRender
    .append('div')
    .classed('sem', true)
    .style('background-color', 'rgba(220, 220, 220, 0.7)')
    .style('padding', '10px 0px')
    .style('margin', '10px')
    .style('border-radius', '20px')
    .style('width', '280px')
    .style('text-align', 'center')
    .html((item, index) => `Sem ${index + 1}`);

  const renderCourse = renderSems
    .selectAll('div')
    .data((item) => item)
    .enter()
    .append('div')
    .style('margin', '10px 0px')
    .append('svg')
    .attr('width', '260px')
    .attr('height', '40px');

  renderCourse
    .append('rect')
    .attr('width', (course) => `${mapStudentByYearRange(course)(course.quantityStudent.year1)}px`)
    .attr('height', '40px')
    .attr('fill', '#0080B8');

  renderCourse
    .append('rect')
    .attr('width', (course) => `${mapStudentByYearRange(course)(course.quantityStudent.year2)}px`)
    .attr('height', '40px')
    .attr('fill', '#009400')
    .attr('x', (course) => `${mapStudentByYearRange(course)(course.quantityStudent.year1)}`);

  renderCourse
    .append('rect')
    .attr('width', (course) => `${mapStudentByYearRange(course)(course.quantityStudent.year3)}px`)
    .attr('height', '40px')
    .attr('fill', '#707000')
    .attr('x', (course) => `${mapStudentByYearRange(course)(course.quantityStudent.year1 + course.quantityStudent.year2)}`);
  renderCourse
    .append('rect')
    .attr('width', (course) => `${mapStudentByYearRange(course)(course.quantityStudent.year4)}px`)
    .attr('height', '40px')
    .attr('fill', '#820013')
    .attr('x', (course) => `${mapStudentByYearRange(course)(course.quantityStudent.year1 + course.quantityStudent.year2 + course.quantityStudent.year3)}`);

  renderCourse
    .append('text')
    .attr('x', 0)
    .attr('y', 20)
    .attr('width', '260px')
    .attr('height', '40px')
    .attr('font', 'bold')
    .attr('fill', 'white')
    .html((d) => d.name);
}

class Statistics extends Component {
  constructor(props) {
    super(props);
  }
  componentDidMount() {
    console.log('YEEET');
    visualizeData();
  }
  render() {
    console.log('RENDER');
    return (
      <div>
        <div id="my-viz" />
      </div>
    );
  }
}

export default Statistics;
