const data_courses = {
  IT101IU: {
    id: "IT101IU",
    name: "Data Structures and Algorithms",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
    selected: false,
  },
  IT102IU: {
    id: "IT102IU",
    name: "Web Application",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: ["IT101IU", "IT103IU"],
    selected: false,
  },
  IT103IU: {
    id: "IT103IU",
    name: "C/C++ Programming",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
    selected: false,
  },
  IT104IU: {
    id: "IT104IU",
    name: "Revolutionary Lines of Vietnamese Communist Party",
    majorId: null,
    subMajorId: null,
    credit: 2,
    prerequisites: [],
    selected: false,
  },
  IT105IU: {
    id: "IT105IU",
    name: "Military Education",
    majorId: null,
    subMajorId: null,
    credit: 0,
    prerequisites: [],
    selected: false,
  },
  IT106IU: {
    id: "IT106IU",
    name: "Software Architecture",
    majorId: "IT",
    subMajorId: "CS",
    credit: 4,
    prerequisites: [],
    selected: false,
  },
  IT107IU: {
    id: "IT107IU",
    name: "Entrepreneurship",
    majorId: "BA",
    subMajorId: null,
    credit: 3,
    prerequisites: [],
    selected: false,
  },
  IT108IU: {
    id: "IT108IU",
    name: "Digital Logic Design",
    majorId: "EE",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
    selected: false,
  },
  IT109IU: {
    id: "IT109IU",
    name: "Object Oriented Programming",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
    selected: false,
  },
  IT_ELECTIVE: {
    id: null,
    name: "Elective",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
    selected: false,
  },
  IT110IU: {
    id: "IT110IU",
    name: "Statistics",
    majorId: "BA",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
    selected: false,
  },
  allIds: [
    "IT101IU",
    "IT102IU",
    "IT103IU",
    "IT104IU",
    "IT105IU",
    "IT106IU",
    "IT107IU",
    "IT108IU",
    "IT109IU",
    "IT_ELECTIVE",
    "IT110IU",
  ],
};

export default data_courses;
