const data_courses = {
  IT101IU: {
    id: "IT101IU",
    name: "Data Structures and Algorithms",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  IT102IU: {
    id: "IT102IU",
    name: "Web Application Development",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: ["IT101IU", "IT103IU"],
  },
  IT103IU: {
    id: "IT103IU",
    name: "C/C++ Programming",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  IT104IU: {
    id: "IT104IU",
    name: "Functional Programming",
    majorId: "IT",
    subMajorId: null,
    credit: 2,
    prerequisites: [],
  },
  IT105IU: {
    id: "IT105IU",
    name: "Digital Image Processing",
    majorId: "IT",
    subMajorId: null,
    credit: 0,
    prerequisites: [],
  },
  IT106IU: {
    id: "IT106IU",
    name: "Software Architecture",
    majorId: "IT",
    subMajorId: "CS",
    credit: 4,
    prerequisites: [],
  },
  IT107IU: {
    id: "IT107IU",
    name: "Entrepreneurship",
    majorId: "IT",
    subMajorId: null,
    credit: 3,
    prerequisites: [],
  },
  IT108IU: {
    id: "IT108IU",
    name: "Digital Logic Design",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  IT109IU: {
    id: "IT109IU",
    name: "Object Oriented Programming",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  IT110IU: {
    id: "IT110IU",
    name: "Artificial Intelligence",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  IT_ELECTIVE: {
    id: "IT_ELECTIVE",
    name: "Elective",
    majorId: "IT",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  EE101IU: {
    id: "EE101IU",
    name: "Introduction to EE",
    majorId: "EE",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  EE102IU: {
    id: "EE102IU",
    name: "Electric Devices",
    majorId: "EE",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  EE103IU: {
    id: "EE103IU",
    name: "Digital Logic Design",
    majorId: "EE",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  BA101IU: {
    id: "BA101IU",
    name: "Introduction to BA",
    majorId: "BA",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  BA102IU: {
    id: "BA102IU",
    name: "Math for Business",
    majorId: "BA",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  BA103IU: {
    id: "BA103IU",
    name: "Statistics",
    majorId: "BA",
    subMajorId: null,
    credit: 4,
    prerequisites: [],
  },
  allIds: [
    "IT101IU",
    "IT102IU",
    "IT103IU",
    "IT104IU",
    "IT105IU",
    "IT106IU",
    "IT107IU",
    "IT108IU",
    "IT109IU",
    "IT110IU",
    "IT_ELECTIVE",
    "EE101IU",
    "EE102IU",
    "EE103IU",
    "BA101IU",
    "BA102IU",
    "BA103IU",
  ],
};

export default data_courses;
