const data_courses = {
  CH011IU: {
    id: 'CH011IU',
    name: 'Chemistry for Engineer',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  CH012IU: {
    id: 'CH012IU',
    name: 'Chemistry Laboratory',
    majorId: null,
    subMajorId: null,
    credit_theory: 0,
    credit_lab: 1,
    prerequisites: [],
  },
  EN007IU: {
    id: 'EN007IU',
    name: 'Writing AE1',
    majorId: null,
    subMajorId: null,
    credit_theory: 2,
    credit_lab: 0,
    prerequisites: [],
  },
  EN008IU: {
    id: 'EN008IU',
    name: 'Listening AE1',
    majorId: null,
    subMajorId: null,
    credit_theory: 2,
    credit_lab: 0,
    prerequisites: [],
  },
  IT135IU: {
    id: 'IT135IU',
    name: 'Introduction to Data Science',
    majorId: null,
    subMajorId: null,
    credit_theory: 4,
    credit_lab: 0,
    prerequisites: [],
  },
  MA001IU: {
    id: 'MA001IU',
    name: 'Calculus 1',
    majorId: null,
    subMajorId: null,
    credit_theory: 4,
    credit_lab: 0,
    prerequisites: [],
  },
  PE015IU: {
    id: 'PE015IU',
    name: 'Philosophy Marx - Lenin',
    majorId: null,
    subMajorId: null,
    credit_theory: 5,
    credit_lab: 0,
    prerequisites: [],
  },
  PH013IU: {
    id: 'PH013IU',
    name: 'Physics 1 (general mechanics)',
    majorId: null,
    subMajorId: null,
    credit_theory: 2,
    credit_lab: 0,
    prerequisites: [],
  },
  PT001IU: {
    id: 'PT001IU',
    name: 'Physical Training 1',
    majorId: null,
    subMajorId: null,
    credit_theory: 1,
    credit_lab: 0,
    prerequisites: [],
  },
  EN011IU: {
    id: 'EN011IU',
    name: 'Writing AE2',
    majorId: null,
    subMajorId: null,
    credit_theory: 2,
    credit_lab: 0,
    prerequisites: [],
  },
  EN012IU: {
    id: 'EN012IU',
    name: 'Speaking AE2',
    majorId: null,
    subMajorId: null,
    credit_theory: 2,
    credit_lab: 0,
    prerequisites: [],
  },
  IT136IU: {
    id: 'IT136IU',
    name: 'Regression Analysis',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT149IU: {
    id: 'IT149IU',
    name: 'Fundamentals of Programming',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT151IU: {
    id: 'IT151IU',
    name: 'Statistical Method',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  MA003IU: {
    id: 'MA003IU',
    name: 'Calculus 2',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  PH014IU: {
    id: 'PH014IU',
    name: 'Physics 2 (Fluid Mechanics and Thermal Physics)',
    majorId: null,
    subMajorId: null,
    credit_theory: 2,
    credit_lab: 0,
    prerequisites: [],
  },
  PT002IU: {
    id: 'PT002IU',
    name: 'Physical Training 2',
    majorId: null,
    subMajorId: null,
    credit_theory: 1,
    credit_lab: 0,
    prerequisites: [],
  },
  IT069IU: {
    id: 'IT069IU',
    name: 'Object-Oriented Programming',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT137IU: {
    id: 'IT137IU',
    name: 'Data Analysis',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT155IU: {
    id: 'IT155IU',
    name: 'Linear Algebra for Data Science',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  PE014IU: {
    id: 'PE014IU',
    name: 'Environmental Science',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  PE016IU: {
    id: 'PE016IU',
    name: 'Marxist – Leninist Political Economy',
    majorId: null,
    subMajorId: null,
    credit_theory: 2,
    credit_lab: 0,
    prerequisites: [],
  },
  IT013IU: {
    id: 'IT013IU',
    name: 'Algorithms and Data Structure',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT079IU: {
    id: 'IT079IU',
    name: 'Principles of Database Management',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT090IU: {
    id: 'IT090IU',
    name: 'Object-oriented analysis and design',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT138IU: {
    id: 'IT138IU',
    name: 'Data Science and Visualization',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  PE017IU: {
    id: 'PE017IU',
    name: 'Scientific Socialism',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  IT139IU: {
    id: 'IT139IU',
    name: 'Scalable and Distributed Computing',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT140IU: {
    id: 'IT140IU',
    name: 'Fundamental Concepts of Data Security',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  MA026IU: {
    id: 'MA026IU',
    name: 'Probability, Statistic & Random Process',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  PE008IU: {
    id: 'PE008IU',
    name: 'Critical Thinking',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  PE018IU: {
    id: 'PE018IU',
    name: 'History of Vietnamese Communist Party',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  IT097IU: {
    id: 'IT097IU',
    name: 'Introduction to Artificial Intelligence',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT132IU: {
    id: 'IT132IU',
    name: 'Introduction to data mining',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  IT142IU: {
    id: 'IT142IU',
    name: 'Analytics for Observational Data',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  ITDS1: {
    id: 'ITDS1',
    name: 'Elective DS1',
    majorId: null,
    subMajorId: null,
    credit_theory: 0,
    credit_lab: 0,
    prerequisites: [],
  },
  PE019IU: {
    id: 'PE019IU',
    name: "Ho Chi Minh's Thoughts",
    majorId: null,
    subMajorId: null,
    credit_theory: 2,
    credit_lab: 0,
    prerequisites: [],
  },
  IT082IU: {
    id: 'IT082IU',
    name: 'Internship',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  IT083IU: {
    id: 'IT083IU',
    name: 'Special Study of the Field',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 0,
    prerequisites: [],
  },
  IT143IU: {
    id: 'IT143IU',
    name: 'Fundamentals of Big Data Technology',
    majorId: null,
    subMajorId: null,
    credit_theory: 3,
    credit_lab: 1,
    prerequisites: [],
  },
  ITDS2: {
    id: 'ITDS2',
    name: 'Elective DS2',
    majorId: null,
    subMajorId: null,
    credit_theory: 0,
    credit_lab: 0,
    prerequisites: [],
  },
  ITDS3: {
    id: 'ITDS3',
    name: 'Elective DS3',
    majorId: null,
    subMajorId: null,
    credit_theory: 0,
    credit_lab: 0,
    prerequisites: [],
  },
  IT058IU: {
    id: 'IT058IU',
    name: 'Thesis',
    majorId: null,
    subMajorId: null,
    credit_theory: 10,
    credit_lab: 0,
    prerequisites: [],
  },
  allIds: ['IT101IU'],
};

export default data_courses;
