// export const FETCH_STATISTIC_GRADING_PENDING = 'FETCH_STATISTIC_GRADING_PENDING';
// export const FETCH_STATISTIC_GRADING_SUCCESS = 'FETCH_STATISTIC_GRADING_SUCCESS';
// export const FETCH_STATISTIC_GRADING_ERROR = 'FETCH_STATISTIC_GRADING_ERROR';

export const GENERATE_RANDOM_COURSE_DATA = 'courses/GENERATE_RANDOM_COURSE_DATA';
export const CLEAR_REDUCER_COURSE = 'courses/CLEAR_REDUCER_COURSE';
export const SELECT_COURSE = 'courses/SELECT_COURSE';
export const REMOVE_SELECTED_COURSE = 'courses/REMOVE_SELECTED_COURSE';
export const SELECT_COURSES = 'courses/SELECT_COURSES';
export const ADD_COURSES = 'courses/ADD_COURSES';
